### ISSUE TITLE
unused sampler

### ISSUE THREAD

**Issue by FyiurAmron** [ogxd/grid-shader-unity#5]
there's the
```
         sampler2D _GridTexture;
         float4 _GridTexture_ST;
```
sampler/texture, but it doesn't seem to be used anywhere. I assume this was intended to be implemented in some way, but currently (unless I'm missing something obvious here) I don't see it handled anywhere in the code, and it's neither set nor accessed anywhere.

**Comment by ogxd** [comment]
Indeed, will remove this.

**Comment by ogxd** [comment]
Done 21f7b7c0db4d9bd84e6b75435450e770e1dd04cc
