### ISSUE TITLE
Consider renaming _BackgroundColor (or _MainColor) to _Color

### ISSUE THREAD

**Issue by FyiurAmron** [ogxd/grid-shader-unity#7]
as per https://docs.unity3d.com/ScriptReference/Material.SetColor.html , having the property name for the "main" color in the shader set to `_Color` makes it essentially the 'main' color as far as Unity internals are concerned, allowing easy access to it from code. Arguably, the background color is the main (dominant) color of the grid.

Alternatively, do that with `_MainColor` instead, if you consider it the 'main' color of this shader. Of course, the string descriptions for them can (and probably should) remain unchanged.

**Comment by ogxd** [comment]
Do you mean turning this:
```shader
_MainColor("Main Color", Color) = (0.5, 1.0, 1.0)
_SecondaryColor("Secondary Color", Color) = (0.0, 0.0, 0.0)
_BackgroundColor("Background Color", Color) = (0.0, 0.0, 0.0, 0.0)
_MaskTexture("Texture", 2D) = "white" {}
```
into this?
```shader
_Color("Main Color", Color) = (0.5, 1.0, 1.0)
_SecondaryColor("Secondary Color", Color) = (0.0, 0.0, 0.0)
_BackgroundColor("Background Color", Color) = (0.0, 0.0, 0.0, 0.0)
_MaskTexture("Texture", 2D) = "white" {}
```

> Arguably, the background color is the main (dominant) color of the grid.

To me the main color shall be the current of the grid lines. The background is by default transparent (which is probably what users want in 90% of usecases) thus it is really a main color but rather just a secondary setting.   

But regarding renaming `_MainColor` to `_Color`, if this is what you meant, I'm all in for it, it's a good idea.

**Comment by FyiurAmron** [comment]
yeah, I don't have a strong opinion whether of those two is actually "main", and I guess that would indeed depend on the exact use case. Even if it's `_MainColor` -> `_Color` , it's good enough I'd say.
